<?php

namespace ceepkev77\cloudbridge\network\packet;

use ceepkev77\cloudbridge\network\DataPacket;
use ceepkev77\cloudbridge\network\RequestPacket;

class ListCloudPlayersResponsePacket extends RequestPacket
{

    public array $players = [];

    public function getPacketName(): string
    {
        return "ListCloudPlayersResponsePacket";
    }

    public function handle()
    {
        $this->players = json_decode($this->data["players"], true);
        parent::handle(); // TODO: Change the autogenerated stub
    }

}