<?php

namespace ceepkev77\cloudbridge\network\packet;

use ceepkev77\cloudbridge\network\RequestPacket;

class ListCloudPlayersRequestPacket extends RequestPacket
{

    public function getPacketName(): string
    {
        var_dump("test");
        return "ListCloudPlayersRequestPacket";
    }

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

}