<?php

namespace ceepkev77\cloudbridge\network\packet;

use ceepkev77\cloudbridge\network\DataPacket;
use ceepkev77\cloudbridge\network\RequestPacket;

class ListServerRequestPacket extends RequestPacket
{

    public function getPacketName(): string
    {
        return "ListServerRequestPacket";
    }

    public function handle()
    {
        parent::handle(); // TODO: Change the autogenerated stub
    }

}