<?php

namespace ceepkev77\cloudbridge\network\packet;

use ceepkev77\cloudbridge\network\DataPacket;

class PlayerMessagePacket extends DataPacket
{
	public $playerName;
	public $value;

	public function getPacketName(): string
	{
		return "PlayerMessagePacket";
	}

	public function encode() {
		$this->addValue("playerName", $this->playerName);
		$this->addValue("value", $this->value);
		return parent::encode(); // TODO: Change the autogenerated stub
	}

}