<?php

namespace ceepkev77\cloudbridge\network\packet;

use ceepkev77\cloudbridge\CloudBridge;
use ceepkev77\cloudbridge\network\DataPacket;

class ProxyPlayerJoinPacket extends DataPacket
{

    public function getPacketName(): string
    {
        return "ProxyPlayerJoinPacket";
    }

    public function handle()
    {
        CloudBridge::$qeueuPlayer[] = $this->data["playerName"];
        parent::handle(); // TODO: Change the autogenerated stub
    }

}