<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 30.05.2021
 * Time: 18:47
 */


namespace battleoase\battlecore\replaySystemPlayer\gui;


use battleoase\battlecore\replaySystemPlayer\entities\HumanEntity;
use battleoase\battlecore\replaySystemPlayer\manager\Replay;
use battleoase\battlecore\replaySystemPlayer\ReplaySystemPlayer;
use formBridge\form\Form;
use formBridge\form\MenuForm;
use formBridge\form\MenuOption;
use pocketmine\player\Player;

class teleportToPlayerGui extends MenuForm
{


    private array $player = [];
    /** @var \pocketmine\entity\Entity[] */
    private array $entites = [];

    public function __construct()
    {
        $this->entites = ReplaySystemPlayer::getInstance()->getReplay()->getLevel()->getEntities();
        $this->player = [];
        $buttons = [];
        foreach ($this->entites as $entity) {
            if($entity instanceof HumanEntity) {
                $buttons[] = new MenuOption($entity->getNameTag());
                $this->player[] = $entity;
            }
        }
        parent::__construct("§6§lTeleporter", "", $buttons);
    }

    public function onSubmit(Player $player): ?Form
    {
        if(isset($this->player[$this->getSelectedOptionIndex()])) {
            $entity = $this->player[$this->getSelectedOptionIndex()];
            if($entity instanceof HumanEntity) {
                $player->teleport($entity->getPosition()->asVector3());
            }
        }
        return parent::onSubmit($player); // TODO: Change the autogenerated stub
    }

    public function onClose(Player $player): ?Form
    {
        return parent::onClose($player); // TODO: Change the autogenerated stub
    }

}